[project]
name = "py-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Taiga Saito", email = "me@taigasaito.org" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
